### PR TITLE
Update README installation instructions

### PR DESCRIPTION
**Pull request by fiskhest**
As a result of implementing #1, I now want to add it to my favourite package repository. I have uploaded the package `bspi-git` to AUR (source repo available at https://github.com/fiskhest/aur-bspi-git) and am now suggesting these modifications of the installation procedure to the README.

Also realised we'd overlooked one of the todo bullets in #1. :tada: :smiley:

### CODE REVIEW

**Comment by aerosol** [comment]
Awesome!

I installed the package via `yay`, but I would expect it to either find the default configuration or point the user at a copy (e.g. in `/usr/share/`) upon fresh installation. Preferably the latter, because `/usr/bin` is not a good place to store config files?

```
$ bspi_listen
No file was found at the specified path for the configuration file
path: /usr/bin/bspi.ini
```

**Comment by fiskhest** [comment]
I updated the AUR package to place a copy of the configuration at `/usr/share/doc/bspi/bspi.ini` and print installation instructions on post-install, and modified the README of this repo based on your feedback. Thanks!

**Comment by aerosol** [comment]
Yaay

**Comment by fiskhest** [comment]
:tada: Cheers @aerosol , I promise I won't be bothering for some time now. :laughing:

**Comment by aerosol** [comment]
Great stuff @fiskhest, anytime!

**Pull request merged**
